### ISSUE TITLE
frame videoplayer does not load on browser

### ISSUE THREAD

**Issue by ph4un00b** [jamons/youtuba#7]
![issue-1](https://cloud.githubusercontent.com/assets/1057021/12634768/240ce76c-c542-11e5-9873-f3189fd4bea5.jpg)
- that's the request needed
- this happen when you refresh the page

**Comment by ph4un00b** [comment]
@Jefdef @franciscotv

**Comment by Jefdef** [comment]
once the search-view has been loaded call the api-iframe
